# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0007_temperature_motor_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temperature',
            new_name='Weather',
        ),
    ]
