# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0008_auto_20171031_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value1', models.CharField(max_length=250)),
                ('hum_value1', models.CharField(max_length=250)),
                ('soil_value1', models.CharField(max_length=250)),
                ('rain_value1', models.CharField(max_length=250)),
                ('water_value1', models.CharField(max_length=250)),
                ('motor_value1', models.CharField(max_length=250)),
            ],
        ),
    ]
